### PR TITLE
feat/refactor: add functionality to preserve original file names

### PR DESCRIPTION
**Pull request by kostamilorava**
## Summary

For image SEO optimisation and generally handling file structure, I have made few changes:

- Pending files will be placed in separate folder, instead of directly putting it on disk
- Updated migration of pending files. It will include original file name as well
- Media library will take original name to save final image that will be used in slider

- #43

### CODE REVIEW

**Comment by ItsANameToo** [comment]
hi @kostamilorava , thanks for this. Could you add a testcase for this as well that shows it stores a pending file in the right location?

**Comment by kostamilorava** [comment]
Hey, @ItsANameToo,

I have slightly refactored tests, adjusted it to new structure and added new test that makes sure file name is correct.

Also, I updated readme. Had issue when nova already included mentioned migrations. So there was no need to add them manually. Instead, I added new column in table.

**Comment by ItsANameToo** [comment]
awesome, I'll try to have a look today!

**Comment by ItsANameToo** [comment]
code wise it looks good @kostamilorava . Will play around with it tomorrow in one of our projects as a final test

**Comment by kostamilorava** [comment]
Awesome, thanks!

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
